### ISSUE TITLE
Convert app to Swift 5

### ISSUE THREAD

**Issue by vatsalkul** [systers/PowerUp#322]
## Description
As a developer,
I want to run project in latest swift,
so that I can write updated code in swift 5.

## Mocks
N/A

### Update [Required]
- [ ] App can be built successfully with no errors or warning after converting to swift 5.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by sunjunkie** [comment]
Where was that screen shot taken? Currently Powerup-iOS successfully builds with xCode 10.2.1  targeting Swift 4.0 and runs successfully on the latest iOS (12).

**Comment by vatsalkul** [comment]
My copy of powerUp is out of sync from the upstream due to some reason, It is solved now. But conversion to swift 5 is available now, can I make a PR for that and edit this issue's description?

**Comment by vatsalkulshreshtha** [comment]
Can I work on this issue and submit a PR?

**Comment by vatsalkul** [comment]
Can I work on this issue and submit a PR?

**Comment by sunjunkie** [comment]
Yes, go ahead. In the future, I think it would be better to close the issue and create a new one.

**Comment by vatsalkul** [comment]
> Yes, go ahead. In the future, I think it would be better to close the issue and create a new one.

Sure!! I will keep that in mind.
