### ISSUE TITLE
Add Contact section to README

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#324]
## Description
Adding a "Contact" section for future contributors to reach out with their questions about active projects within the community. Additional instructions on how to reach out to maintainers of this project on GitHub and on Zulip.

```
## Contact

You can reach maintainers team in our [AnitaB.org Open Source Zulip](http://anitab-org.zulipchat.com/) or @anitab-org/powerup-maintainers on GitHub.

We use [#powerup stream](https://anitab-org.zulipchat.com/#narrow/stream/222537-powerup) stream on Zulip to discuss this project. If you're interested in contributing to this project, join us there!

```

I need to add an additional Contact section,
so that anyone who has questions about PowerUp iOS or want to contribute to the project can join the Zulip community.

### Update [Required]
- [ ] Update the ReadMe.md with the code included above at the very bottom of the ReadMe.md file.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by mayburgos** [comment]
I'm going to wait on this. Not because you're incorrect. It's true. We don't have information on how to get involved through Slack.

But I'm not sure if we're continuing the communication through Slack.

**Comment by anubhavpulkit** [comment]
> I'm going to wait on this. Not because you're incorrect. It's true. We don't have information on how to get involved through Slack.
> 
> But I'm not sure if we're continuing the communication through Slack.

ok.

**Comment by anubhavsingh16** [comment]
@mayburgos @sunjunkie  Any update about this Issue?

**Comment by anubhavpulkit** [comment]
@mayburgos Can I send my PR now with an updated communication channel.

**Comment by anubhavpulkit** [comment]
@sunjunkie please have a look

**Comment by sunjunkie** [comment]
I defer to @mayburgos on this issue.

**Comment by mayburgos** [comment]
Thanks @sunjunkie! 

@anubhavsingh16  Can you mentor a beginner on this issue? I think it's very simple and would benefit someone who's beginning in open source.

I've also updated the original issue's details.

**Comment by anubhavpulkit** [comment]
@mayburgos Ok

**Comment by isabelcosta** [comment]
This was completed with PR #379
