### ISSUE TITLE
Continue button is running out of screen in iPhone 11 Pro Max 

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#327]
## Description
To Continue the game, Continue button is used which is not at a proper place. Some part of the Continue button is out of the screen when we open in iPhone 11 Pro Max Simulator in Orientation Landscape Right.  

## Mocks
[
![systers](https://user-images.githubusercontent.com/47811606/73120308-44c8b200-3f92-11ea-8cab-fb5849e09d5e.png)
 ]

### Update [Required]
- [ ] [Change the positon of button]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie what about this one?

**Comment by sunjunkie** [comment]
OK. Be sure to test all iPhone sizes. Use the iOS "safe area" as the alignment guide for the button location.

**Comment by anubhavpulkit** [comment]
> OK. Be sure to test all iPhone sizes. Use the iOS "safe area" as the alignment guide for the button location.

@sunjunkie "safe area" is only implemented in ios-11 or letter but our app is run at iOS-9.
So we do not use the "safe area" guideline while we put at a place where it looks far better.

**Comment by sunjunkie** [comment]
You're right! So let's set the minimum iOS support to 11. Today, 93% of all active iPhones are running ios 12 or 13 so there is no reason we need to continue iOS 10 support. I will create an issue to set the minimum iOS support to iOS 11. Let's fix that one first and then fix this one with the safe area. That will make it easier to support iphone sizes in the future. 
By the way, your pull request for issue #288 is not complete. See my comments on your pull request. I am going to close issue #288 and create a new one for iOS 11 to supercede that.

**Comment by anubhavpulkit** [comment]
@sunjunkie solve in Pull Request #333
