### ISSUE TITLE
Error in Library Game

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#328]
## Description
The game which is present in Library after the interaction has errors, In the block where questions are displayed by some typo error it shows backend result file in all 10 questions.

## Mocks
[
![systers 2](https://user-images.githubusercontent.com/47811606/73125279-1fa46580-3fcb-11ea-8827-e06761feacb8.png)
]

### Update [Required]
- [ ] [change the values of variable which shows questions]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by sunjunkie** [comment]
Are you talking about the text "Test question: 7; answer: false"? This is as expected since we don't have actual content for the app yet.

**Comment by anubhavpulkit** [comment]
> Are you talking about the text "Test question: 7; answer: false"? This is as expected since we don't have actual content for the app yet.

ok, I thought this is an error.
