### ISSUE TITLE
Set minimum iOS support to 11.0

### ISSUE THREAD

**Issue by sunjunkie** [systers/PowerUp#331]
## Description
As a developer,
I want to set the minimum iOS support to iOS 11,
so that I can remove unnecessary code and take advantage of newer iOS features.

## Notes:
As of January 30, 2020, 93% of iOS devices are running iOS 12 or iOS 13. (iOS tends to have a high rate of upgrade adoption.) Moving to iOS 11 will enable us to take advantage of new layout features in iOS 11+.

### Update [Required]
- [ ] project supports iOS 11 and above.
- [ ] all availability conditions that test for older iOS version are removed.
- [ ] code specifically for iOS versions 10 or earlier is removed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I also change the Project Format form Xcode 3.2-Compatible to Xcode 9.3-Compatible
