### ISSUE TITLE
Update link of Docs.

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#337]
## Description
As a user when I open [Links to the Documentation of 2016](https://github.com/anitab-org/powerup-iOS#documentation-of-powerup-ios) which is present at the end of Readme.
The Content which is present inside the [Link](https://docs.google.com/document/d/1N_-zmmjPn6D1H6wTdF4z66mFGT3af_FWbfGvLKkeY1w/edit) has some error.
I need to remove the Links to the Documentation of 2016. so that Readme is free from this error.

## Mocks
![error](https://user-images.githubusercontent.com/47811606/74512808-19047080-4f2f-11ea-80e4-41468ab7aafb.png)

**All the content is broken.**

![error2](https://user-images.githubusercontent.com/47811606/74512831-24579c00-4f2f-11ea-91eb-785b83807713.png)

### Update [Required]
- [x] [Link update]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.5] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie Please have a look at this issue.

**Comment by anubhavpulkit** [comment]
@isabelcosta This issue is not solved please add labels for first-timer only.

**Comment by isabelcosta** [comment]
@anubhavsingh16 I don't understand this issue, can you elaborate more? The link you show is about GSoC16 documentation, but you talk about git commands on the issue description 😕

**Comment by sunjunkie** [comment]
So if you go to the link and set Viewing mode to "Viewing", the doc comes up just fine. We  need to keep a link to this document for historical purposes. I don't use Google docs. Is there a way to create a new link does not give universal editing or commenting access?  Otherwise we could copy the doc and repost it without editing access.

**Comment by anubhavpulkit** [comment]
Yes after set Viewing mode to "Viewing" the doc comes up just fine.
And Yes there is a way to create a new link of doc and does not give universal editing and commenting access.

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I send a PR for this issue to change doc link and change access settings.

**Comment by sunjunkie** [comment]
Yes.

**Comment by anubhavpulkit** [comment]
thank You @sunjunkie
