### ISSUE TITLE
Smoke coming out of the house's chimney is overlaped by school

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#344]
## Description
A small error in which the school overlaps the smoke coming out of the house's chimney In the map.

## Mocks
![powerup](https://user-images.githubusercontent.com/47811606/75070945-5ada7b80-551a-11ea-8f9e-f40c1d895552.png)

### Update [Required]
- [ ] [Changes in constrant of school in Map]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie please have a look.

**Comment by MANI14011998** [comment]
Hey @anubhavsingh16  I am opening that issue too I have completed that too so can you passes it too me .
Thank you

**Comment by anubhavpulkit** [comment]
@MANI14011998 Sorry but this issue is not approved by mentor @sunjunkie and I open this issue because I'm also working on this issue. Sorry @MANI14011998 please visit https://github.com/anitab-org/powerup-iOS/issues

**Comment by MANI14011998** [comment]
Ok @anubhavsingh16  if you really wants to work on it or investing your time in that thing which is already done you can go ahead ...

**Comment by sunjunkie** [comment]
This issue is part of issue #264
