### ISSUE TITLE
Adding New Feature In the ShopView Wheel of Fortune 

### ISSUE THREAD

**Issue by MANI14011998** [systers/PowerUp#350]
## Description
As a User,
What If my karma Point is Just not enough to Buy new Item , Adding new feature Wheel Of fortune Button On the Bottom Of Home Button ,So when Ever User Clicks that a wheelViewController Or View , It Will appear And Gives The extra Point ,Knowing that it is Important not to Give too Much Free karma Points ,I will Add timer in it lets Say once in 8hour and karma point would be less. 
so can  I work on this Idea .

## Mocks
![Screenshot 2020-02-25 at 5 08 28 PM](https://user-images.githubusercontent.com/34857581/75244281-88147b80-57f1-11ea-945e-dc5e5a2eea4f.png)

## Acceptance Criteria
- increase interest of user 
- adding extra feature In the app
- animations 
### Approach
- Work On sqlLite .
- make assets according to Style Guide Line

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
24 hours

**Comment by MANI14011998** [comment]
@sunjunkie  ma'am is that Idea is Good ?
After Getting Approval  I will give you the asset design as well  to approve the design as well ..
Ps - the Design In MockUp Is not just a reference I will give You Better Design

**Comment by sunjunkie** [comment]
This is an entirely new feature which is really unnecessary at this point. We really need to improve the current state of the app to get it ready for production. Also, you do not state why the user would need this. Look at the issue template. https://github.com/anitab-org/powerup-iOS/blob/develop/ISSUE_TEMPLATE.md

**Comment by MANI14011998** [comment]
Oh really sorry ma'am I am not saying that it's necessary just I am increasing the gaming thing 
And I will follow the template next time sorry for inconvenience ma'am
