### ISSUE TITLE
Problem in size of boxes of MinesweeperGame

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#351]
## Description
In Minesweeper game, we define boxSize = Double(size.width) * boxSizeRelativeToWidth this equetion is not fit for some screen size. Especially for screen size of iPhone X and above models boxSize is too large and create an annoying view.

## Mocks
![systers issue 222](https://user-images.githubusercontent.com/47811606/75451945-60f7ae80-5997-11ea-946c-051235088b48.png)

### Update [Required]
- [ ] [Changes in boxSize formula]
- [ ] [Changes in newBox.position]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[6] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie Please have a look, I think I solve this issue up to tomorrow. The equation which we are using for box size is only applicable up to the iPhone 8 plus devices.

**Comment by MANI14011998** [comment]
this issue comes under #264 @anubhavsingh16

**Comment by anubhavpulkit** [comment]
@sunjunkie @MANI14011998  Ok so can I do that part-out of them or close this issue because in this issue assets are not required.

**Comment by sunjunkie** [comment]
See my comments in issue #264
