### ISSUE TITLE
Score label of Vocab Matching is not clearly visible

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#352]
## Description
Score label which is at the left-most corner is not visible clearly because of the curved-screen in iPhone X devices, `S` of Score is hidden.

## Mocks
![mineskipper 2](https://user-images.githubusercontent.com/47811606/75468352-1be17580-59b3-11ea-9a8f-f21109179802.png)

### Update [Required]
- [x] [Changes in scoreBoxSpriteWidth value]
- [x] [Changes in scoreBoxSpritePosY value]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie please have a look.

**Comment by sunjunkie** [comment]
@anubhavsingh16 Please edit the description to provide an estimate of hours. Also, remember to set the position using the safe area.

**Comment by anubhavpulkit** [comment]
Ok, thanks @sunjunkie
