### ISSUE TITLE
Start View Scene does not support multiple screen aspect ratio

### ISSUE THREAD

**Issue by vatsalkul** [systers/PowerUp#355]
## Description
As a user,
I need not to see extra blank space on my screen when opening the game for first time, there is a scope of improvement in UI and UX.
Start View is looking perfect on iPhone 8 Plus and below, but not on iPhone X or above.

## Mocks
<img width="797" alt="Screenshot 2020-02-29 at 3 20 13 PM" src="https://user-images.githubusercontent.com/30840527/75605242-1a28c680-5b07-11ea-903f-ab9ac2202849.png">

## Acceptance Criteria

The Start View Scene should look like this on iPhone X and above:
<img width="791" alt="Screenshot 2020-02-29 at 3 08 41 PM" src="https://user-images.githubusercontent.com/30840527/75605229-ff565200-5b06-11ea-95ce-a3c0c64c6520.png">

### Update [Required]
- [ ] Check and update image assets where appropriate
- [ ]  Update full screen asses (such as backgrounds) to be aspect ratio agnostic (maybe extra neutral space around the edges)
- [ ]  Update storyboard layouts to use the new visual assets
  
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by vatsalkul** [comment]
@sunjunkie Please review and allow me to send PR. 😇

**Comment by sunjunkie** [comment]
@vatsalkul You can work on this.
