### ISSUE TITLE
Background image of Avatar view, Map View, Completed view, Scenario view and End view controller is not cover full screen in iPhone X models

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#360]
## Description
Background image of Avatar view, Map View, Completed view, Scenario view and End view controller are not in full screen because of we use safe-area alignment on background also it does not look as we want.

## Mocks

![systers987a](https://user-images.githubusercontent.com/47811606/75631143-69115180-5c16-11ea-879b-4ceeba25b0b8.png)

![syster987b](https://user-images.githubusercontent.com/47811606/75631148-70d0f600-5c16-11ea-9ae2-77b743964858.png)

![syster987c](https://user-images.githubusercontent.com/47811606/75631154-79c1c780-5c16-11ea-9963-18754a1b620a.png)

![systers987d](https://user-images.githubusercontent.com/47811606/75631171-8fcf8800-5c16-11ea-8933-7e529dea4cfe.png)

![syster1](https://user-images.githubusercontent.com/47811606/75631174-95c56900-5c16-11ea-8f7e-e79dc6704ac4.png)

### Update [Required]
- [x] [update background constraints ]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie please have a look.

**Comment by anubhavpulkit** [comment]
@sunjunkie can you please review this issue.

**Comment by sunjunkie** [comment]
@anubhavsingh16 This issue scope is too big - it overlaps with other issues being worked on. Create an issue for one screen at a time. Make sure it is not part of another issue.

**Comment by anubhavpulkit** [comment]
@sunjunkie ok

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I make changes in two at a time in Avtar and end screen?

**Comment by sunjunkie** [comment]
Create an issue for each one separately.

**Comment by anubhavpulkit** [comment]
Ok Thank You @sunjunkie
