### ISSUE TITLE
Background image of Avatar view is not cover full screen in iPhone X models.

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#361]
## Description
Background image of Avatar view controller is not in full screen because of we use safe-area alignment on background also it does not look as we want.

## Mocks
![systers issue](https://user-images.githubusercontent.com/47811606/75802752-3f396580-5da3-11ea-8678-c8a8af13e1dc.png)

### Update [Required]
- [x] [update background constraints ]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I add `Completed view`, and `End view` controller in this issue because of no one working on these views.

**Comment by sunjunkie** [comment]
No, let's keep them separate.

**Comment by anubhavpulkit** [comment]
Ok, @sunjunkie  Can I send PR for this one?

**Comment by sunjunkie** [comment]
yes

**Comment by anubhavpulkit** [comment]
Thank You @sunjunkie I don't know why but I'm so happy when I have the approval to send PR🤓

**Comment by sunjunkie** [comment]
This issue no longer exists.
