### ISSUE TITLE
Background image of Result view Controller is not cover full screen in iPhone X models

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#362]
## Description
Background image of the Result view controller is not in full screen because of we use safe-area alignment in Trailing, Leading, Bottom and top of the background image so it does not look as we want.

## Mocks
![sys 3848](https://user-images.githubusercontent.com/47811606/75822734-72412080-5dc6-11ea-90e9-996b2eb3c002.png)

### Update [Required]
- [x] [update background constraints to Superview]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[30] min

**Comment by anubhavpulkit** [comment]
Sorry, @sunjunkie I forget that I removed Completed View Controller.

**Comment by anubhavsingh16** [comment]
@YuChaoGithub Can I send my Pull Request?

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I send PR for this issue?

**Comment by sunjunkie** [comment]
@anubhavsingh16 Yes you can.

**Comment by anubhavpulkit** [comment]
Ok, Thank You @sunjunkie
