### ISSUE TITLE
Background image of End view Controller is not cover full screen in iPhone X models

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#363]
## Description
Background image of End view controller is not in full screen because of we use safe-area alignment in Trailing, Leading, Bottom and top of the background image so it does not look as we want.

## Mocks
![systers987a](https://user-images.githubusercontent.com/47811606/75823031-06ab8300-5dc7-11ea-932b-63f694da156e.png)

### Update [Required]
- [x] [update background image constraints to Superview for all conditions]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[30] min.

**Comment by anubhavpulkit** [comment]
@sunjunkie Is it ok too right to write the same description in all three issues?

**Comment by sunjunkie** [comment]
You must use the safe area in iOS. That is the safest and easiest way to position UI elements for all screen sizes.  For one, our app should never cover the home indicator line in iPhone X and newer. There are ways to design the screen to look good using safe area.

**Comment by anubhavpulkit** [comment]
@sunjunkie I think we use safe-area for UILabels, Buttons... which are functional. I think for background image if we use Superview then it more accurate and look good.

**Comment by sunjunkie** [comment]
@anubhavsingh16 Yes, I like your plan.

**Comment by anubhavpulkit** [comment]
So can I send my PR?

**Comment by sunjunkie** [comment]
yes, whenever you are ready
