### ISSUE TITLE
First letter of text in the storySequence is visible in X modes

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#364]
## Description
First letter of story sequence is hidden by the notch in X and new models.

## Mocks
![systers issue sequence story](https://user-images.githubusercontent.com/47811606/75871796-237da000-5e33-11ea-8f2f-a7d997339e5c.png)

![systers issue story sequence 3](https://user-images.githubusercontent.com/47811606/75871819-2a0c1780-5e33-11ea-8b2e-ffd0aa3bf3c7.png)

### Update [Required]
- [x] [add safe area constraints in story sequence]

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by anubhavpulkit** [comment]
@sunjunkie please have a look.

**Comment by sunjunkie** [comment]
You can work on this.

**Comment by anubhavpulkit** [comment]
Thank You @sunjunkie

**Comment by sunjunkie** [comment]
@aviralx10 You can work on this.

**Comment by aviralx10** [comment]
Thank you @sunjunkie

**Comment by sunjunkie** [comment]
@anubhavsingh16 In the future, please work on one issue at a time. If you can't fix the issue within a reasonable amount of time, let me know or it will be assigned to someone else. I'll review your PR.
@aviralx10 Please select another issue to work on.

**Comment by anubhavpulkit** [comment]
> @anubhavsingh16 In the future, please work on one issue at a time. If you can't fix the issue within a reasonable amount of time, let me know or it will be assigned to someone else. I'll review your PR.
> @aviralx10 Please select another issue to work on.

Ok Sorry @sunjunkie

**Comment by anubhavpulkit** [comment]
@Aviral190694 issue 345 is free if you want to work and sorry I saw now after sending my PR if you want to give any suggestion or you have any other way to solve this issue then, please discuss it is helpful sorry.

**Comment by anubhavpulkit** [comment]
and you are welcome to send Pull Request for this issue Thank You @aviralx10 and sorry @sunjunkie this is my mistake.

**Comment by aviralx10** [comment]
@anubhavsingh16 ,I just saw your pull request and i had figured out a solution by updating the margin (CG value) :/  ... no problem ..i'll now work on another issue.

**Comment by anubhavpulkit** [comment]
Ok thank you @aviralx10
