### ISSUE TITLE
Change references to systers travis link on README

### ISSUE THREAD

**Issue by isabelcosta** [systers/PowerUp#367]
## Description

The README contains TravisCI link from systers instead of anitab-org. This should be changed on the URL.

### Update [Required]
- [ ] Change references from TravisCI from `systers` account to `anitab-org`.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by AjayThakur12** [comment]
@isabelcosta please assign it to me

**Comment by isabelcosta** [comment]
@AjayThakur12 this is for first timers only for this repository, so please look for other issues.

**Comment by AjayThakur12** [comment]
okay @isabelcosta

**Comment by isabelcosta** [comment]
I just noticed that this was done with #342 
I will close this then
