### ISSUE TITLE
Add Contact section on README

### ISSUE THREAD

**Issue by isabelcosta** [systers/PowerUp#371]
## Description

As a contributor,
I need to know where I can reach out to the community,
so that I can discuss or see discussions of this project.

I would suggest adding a section such as "Contact us" or "How to reach us" to the README.
An example is what is on [mentorship-backend README](https://github.com/anitab-org/mentorship-backend/).

### Update [Required]
- [ ] Add contact section with AnitaB.org Open Source Zulip link and #powerup stream link. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by AjayThakur12** [comment]
@isabelcosta  please assign it to me

**Comment by isabelcosta** [comment]
@AjayThakur12 you can work on this :) I will assign this to you.

**Comment by sunjunkie** [comment]
@AjayThakur12 You need to submit a pull request on *this* repository. See https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request.
