### ISSUE TITLE
Completed View Controller present in Storyboard

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#373]
## Description
After merging Improved Start View #359 Complete View Controller again add in Storyboard.
And by this, we have now we have 2 view controllers (Results View Controller and Completed View Controller) look identical.

### Update [Required]
- [x] [Delete Completed View Controller]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by sunjunkie** [comment]
@anubhavsingh16 Can you please fix this issue before you work on any more? Thank you.

**Comment by anubhavpulkit** [comment]
@sunjunkie This issue is solved automatically when I send PR for Update Scenario view because Updated Scenario view PR is open before @vatsalkul PR.
