### ISSUE TITLE
Some last letter words disappear in iPhone X and later models during dialogue preview

### ISSUE THREAD

**Issue by aviralx10** [systers/PowerUp#374]
<img width="779" alt="Screenshot 2020-03-09 at 11 17 18 AM" src="https://user-images.githubusercontent.com/40929234/76186492-8044d600-61f8-11ea-8063-57ce7b969d60.png">

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by aviralx10** [comment]
I want to work on this issue

**Comment by sunjunkie** [comment]
I think this is the same issue as #364. You can work on that issue.
