### ISSUE TITLE
Karma Points shown incorrectly in Shop

### ISSUE THREAD

**Issue by yugantarjain** [systers/PowerUp#375]
## Description
The Karma points of the player are shown incorrectly in the Shop View. This is happening because the text of the pointsLabel is getting truncated due to size constraints.
Tested on iPhone 7.

## Mocks
![IMG_4D342A693EE5-1](https://user-images.githubusercontent.com/31164725/76212463-8d7cb780-622e-11ea-9846-d5d2aea2c253.jpeg)
**Actual number of Karma Points = 21**  
**Karma points shown = 2**

### Update [Required]
- [ ] The Karma points shall be shown correctly.
- [ ] Constraints of the pointsLabel have to be updated.
### Enhancement to Update [Optional]
- [ ] Text size of pointsLabel must be made dynamic

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[15] minutes

**Comment by sunjunkie** [comment]
I approve this issue.
