### ISSUE TITLE
UI/UX improvements to show selected items in Shop

### ISSUE THREAD

**Issue by yugantarjain** [systers/PowerUp#376]
## Description
As a user,
I need be able to see the items (hair/clothes/accessories) that I've selected,
this is important from a UI/UX point of view and makes the Shop scene more intuitive for me.

## Mocks
![IMG_0362](https://user-images.githubusercontent.com/31164725/76219647-27972c80-623c-11ea-91c0-f5fdef2f58cd.PNG)
### Update [Required]
- [ ] Change label for selected item from 'Select' to 'Selected'
### Enhancement to Update [Optional]
- [ ] Add deselection UI for accessories. 
(Unlike hair and clothes, multiple accessories can be selected)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by sunjunkie** [comment]
I approve this issue.

**Comment by yugantarjain** [comment]
@sunjunkie thank you for approving the issue. 
Before working on it, I wanted to ask you whether the tick mark should be used to signify a bought item or a selected item?

**Comment by sunjunkie** [comment]
I think the tick mark is confusing. Perhaps something like "buy", "purchased", and "selected" for the text might be clearer. What do you think?

**Comment by yugantarjain** [comment]
I think we can use the tick mark for the **selected** items. It may be a good complement to the text for a quick visual feedback.

**Comment by sunjunkie** [comment]
OK, but let's make them smaller and a little less intrusive  so they don't cover the item. 😊
