### ISSUE TITLE
 ABOUT section untidy and not aligned

### ISSUE THREAD

**Issue by aviralx10** [systers/PowerUp#381]
<img width="761" alt="Screenshot 2020-03-11 at 2 11 24 PM" src="https://user-images.githubusercontent.com/40929234/76398134-57f8db00-63a2-11ea-8679-ba5b8753aaf0.png">
<img width="750" alt="Screenshot 2020-03-11 at 2 14 02 PM" src="https://user-images.githubusercontent.com/40929234/76398278-9c847680-63a2-11ea-823f-5badc9f3d84c.png">

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-1.5 hours

**Comment by aviralx10** [comment]
I would like to work on this issue.

**Comment by anubhavpulkit** [comment]
@aviralx10 This issue is already mentioned in the issue list.

**Comment by aviralx10** [comment]
@sunjunkie can i please work on this issue?

**Comment by sunjunkie** [comment]
There is another issue for the About View Controller (#243) and there is a pull request for fixing that (PR #348). Unfortunately, there is a conflict in that PR so it has not been merged yet.
