### ISSUE TITLE
Purchased item gets temporarily unavailable in Shop

### ISSUE THREAD

**Issue by yugantarjain** [systers/PowerUp#383]
## Description
When an item is purchased in the Shop scene, it can get temporarily unavailable for the user and be required to be bought again.
This happens when after purchasing something the accessory category is changed(eg. hair, clothes, accessories) and on returning back the recently purchased item is shown as unowned. 

The underlying reason is that the database is not fetched when a category is changed.

### Temporary workaround
Going to map and coming back to the Shop.

### Update [Required]
- [ ] The database must be fetched every time the category is changed
- [ ] The bug must be fixed and the user shouldn't have to buy an item multiple times
### Enhancement to Update [Optional]
- [ ] Code can be made more efficient

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by sunjunkie** [comment]
I approve this issue.
