### ISSUE TITLE
Size of boxes of Minesweeper games is not fit for iPhone X and latest models.

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#385]
## Description

As a user, I want to see all the boxes in the minesweeper game laid out appropriately on all iPhone sizes, so that I can play the game correctly on any iPhone.

## Mocks
![systers issue 222](https://user-images.githubusercontent.com/47811606/76562280-14e65700-64cb-11ea-9b0f-1f9da437ab0f.png)

### Update [Required]
- [x] [Required change in boxSize equation]
- [x] [Required changes in newBox.position]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by sunjunkie** [comment]
Let's start following the issue template. Specifically:

Description
As a [USER], I need [TO DO THIS], so that I can [ACCOMPLISH THAT].

**Comment by anubhavpulkit** [comment]
@sunjunkie I update the description Can you please have a look.

**Comment by sunjunkie** [comment]
You have to actually use this text specified in the template at the beginning of your description.
As a [USER], I need [TO DO THIS], so that I can [ACCOMPLISH THAT].

You must substitute the correct text for the words in all caps (the placeholder text). So something like: 
As a user, I want to see all the boxes in the minesweeper game layed out appropriately on all iPhone sizes, so that I can play the game correctly on any iPhone.

**Comment by anubhavpulkit** [comment]
Ok, I understand now Thank You @sunjunkie

**Comment by anubhavpulkit** [comment]
@sunjunkie I'm facing a problem as a student I want to discuss with you. Actually, in today's project feedback sessions I'm so nervous and I can not explain my proposal properly. what I can do? Because my English is not good I understand well but can’t speak fluently and because of these language issues I’m nervous and can’t speak anything in the feedback session. Can you give any suggestion?

**Comment by sunjunkie** [comment]
This is not the appropriate venue for that discussion. I will just say that a carefully planned and well-thought-out  proposal carries more weight than a flawless presentation. I would focus on creating a comprehensive, detailed proposal for your application.

**Comment by anubhavpulkit** [comment]
> You have to actually use this text specified in the template at the beginning of your description.
> As a [USER], I need [TO DO THIS], so that I can [ACCOMPLISH THAT].
> 
> You must substitute the correct text for the words in all caps (the placeholder text). So something like:
> As a user, I want to see all the boxes in the minesweeper game layed out appropriately on all iPhone sizes, so that I can play the game correctly on any iPhone.

Done

**Comment by sunjunkie** [comment]
I removed the part about boxsize - that is an implementation detail and does not belong in the user story.

I assigned this to you but please fix #373 first.

**Comment by anubhavpulkit** [comment]
@sunjunkie I send my PR today.Thank You
