### ISSUE TITLE
Background image of Scenario View is not cover the whole screen in iPhone X models

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#386]
## Description
Background image of Scenario View is not cover the whole screen in the latest iPhone models. Because constraints which are used for the background image is not updated.

## Mocks
[
![systers987d](https://user-images.githubusercontent.com/47811606/76568588-26356080-64d7-11ea-9cf5-e6239d24ebb9.png)
]

### Update [Required]
- [x] [Update Constraints of background]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by sunjunkie** [comment]
Issue approved.
