### ISSUE TITLE
Travis CI test cases is not running 

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#390]
## Description
As a user, I saw Travis CI test cases are not working after moving from Systers to AnitaB.org, I need to do changes in Travis CI test link so that Travis CI test run as before.

### Update [Required]
- [x] [changes in Travis CI test link

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by sunjunkie** [comment]
Approved. @anubhavsingh16 do you want to work on this?

**Comment by anubhavpulkit** [comment]
Yes @sunjunkie

**Comment by sunjunkie** [comment]
ok

**Comment by anubhavpulkit** [comment]
@sunjunkie Only members of this organisation add this test to any repo. I'm not approved to add Travis CI test in PowerUp.

**Comment by sunjunkie** [comment]
OK, I'll follow up on this with @mayburgos.

**Comment by anubhavpulkit** [comment]
ok

**Comment by mayburgos** [comment]
@anubhavsingh16 Can you screenshot the error you encountered?

**Comment by anubhavpulkit** [comment]
Hi, @mayburgos actually Cl test is not running when I send PR to PowerUp after we change our domain from Systers to AnitaB.org but from last PR #393  it is automatically running fine.

**Comment by anubhavpulkit** [comment]
You can see the difference in these screenshots

When PowerUp is under Systers organisation CI test works fine you see example in the bottom cases but after the transition from systers to anitaB.org organisation, CI test is not working you can see an example in top cases.
![issue problem CI test](https://user-images.githubusercontent.com/47811606/78811690-d9ff1280-79e7-11ea-82e0-3e990156617d.png)

**Comment by anubhavpulkit** [comment]
but from last PR it works fine automatically you can see the example on the top case.
![Untitled](https://user-images.githubusercontent.com/47811606/78812132-8e009d80-79e8-11ea-9eb2-5a6e0dd51457.png)

**Comment by sunjunkie** [comment]
@anubhavsingh16 Have you tried running the tests on your system?

**Comment by anubhavpulkit** [comment]
@sunjunkie I think we can't run CI test on our systems it is integrated with GitHub.

**Comment by sunjunkie** [comment]
Yes you can. It is an important part of submitting a PR. You must check the boxes when you submit a PR:
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes

See:
https://www.raywenderlich.com/960290-ios-unit-testing-and-ui-testing-tutorial
https://devstreaming-cdn.apple.com/videos/wwdc/2019/413kpguqjv5fqp9/413/413_testing_in_xcode.pdf

**Comment by anubhavpulkit** [comment]
Ok, Thank You @sunjunkie

**Comment by sunjunkie** [comment]
Closed in favor of #399
