### ISSUE TITLE
Make ReadMe.md more interactive

### ISSUE THREAD

**Issue by anubhavpulkit** [systers/PowerUp#395]
## Description
As a user, I want to add some screenshots of PowerUp app, margins and redesign Readme.md
so that [Readme file looks more interactive and decent not so bulky].

### Update [Required]
- [x] [Changes in Readme.md]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[2] hours

**Comment by anubhavpulkit** [comment]
Any newcomer who wants to work on this issue?

**Comment by nandini45** [comment]
yeah i want to @anubhavsingh16

**Comment by anubhavpulkit** [comment]
@isabelcosta Please have a look this issue and assign to @nandini45.

**Comment by isabelcosta** [comment]
done @anubhavsingh16 :)

**Comment by anubhavpulkit** [comment]
@isabelcosta Can I mentor this issue, please.

**Comment by sunjunkie** [comment]
@anubhavsingh16 Regarding the description text ""I need [to do remove some points of Contributing and developing a feature and add some emojis and images]" - this is implementation and does not belong in the user story.

**Comment by anubhavsingh16** [comment]
@sunjunkie is it ok now? and please have a look updated commit of PR #393

**Comment by isabelcosta** [comment]
@anubhavsingh16 what do you mean by mentor exactly? One good thing you could do is be more descriptive and clear in the issue description. If your issue is clear on the Acceptance Criteria and Definition of Done you are closer to helping the contributor understanding by themselves what they need to do ;)

What exactly are you suggesting with this issue, what are some suggestions you have for it to be more "interactive and decent"?

**Comment by sunjunkie** [comment]
The user story starts out "as a user". So what do I want as a user? The user does not care specifically about margins or adding screenshots, for example. What do you think the user wants from the readme that is not there and why? You should answer that question without thinking about how you want to fix the readme. :-)

**Comment by sunjunkie** [comment]
BTW, I deleted one of your comments only because you mentioned an unrelated PR in the comment. That messes up the connections between issues and PRs...

**Comment by anubhavpulkit** [comment]
As a user, I want to understand the PowerUp project in detail and there functions with some images, 
I need [to add some images and remove some unnecessary things from README.md],
so that I can [Understand the function of PowerUp-iOS].

**Comment by anubhavpulkit** [comment]
Actually @sunjunkie if you look out README of PowerUp-iOS, it looks like we describe the functionality of git in Readme, I can't find anything about PowerUp in Readme section.

**Comment by nandini45** [comment]
@anubhavsingh16 can you tell me any specific details which is required or some mandatory features so that i can edit and make the changes

**Comment by anubhavpulkit** [comment]
@nandini45 You have to wait a little bit for approval of this issue.

**Comment by sunjunkie** [comment]
@anubhavsingh16 yes, that’s exactly right. You can’t find anything about Powerup in the readme. *That* is the user’s problem. “Adding images” and “removing unnecessary things” does not describe what the user wants so it doesn’t belong in the user story. The user wants to understand something about the goals and functionality of the Powerup app. The user does not care how you convey that info to them. There are multiple ways to do that: screen shots, more details, videos, tutorials ...

**Comment by sunjunkie** [comment]
I am going to close this. We can start over with a better user story.
