### ISSUE TITLE
Update SQL library for Xcode 11

### ISSUE THREAD

**Issue by sunjunkie** [systers/PowerUp#398]
## Description
As a developer,
I need to use the latest sql library in Xcode,
so that I can continue to develop and run the app in Xcode 11.

## Mocks
<img width="764" alt="Screen Shot 2020-04-20 at 2 33 49 PM" src="https://user-images.githubusercontent.com/399376/79801994-07b35800-8314-11ea-9fcd-62bf2ecdad9d.png">

### Update [Required]
- [x] New library selected in Powerup target (see image)
- [x] Remove libsqlite3.dylib file from project

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
<1 hours

**Comment by anubhavpulkit** [comment]
@sunjunkie Can I work on this issue first?

**Comment by anubhavpulkit** [comment]
@sunjunkie I think in this issue I have to only delete libsqlite3.dylib file from Xcode right?

**Comment by sunjunkie** [comment]
No, there are 2 things listed that must be done. Delete the file and select the new library in the Powerup target in the Build Phases tab as shown in the image.

**Comment by anubhavpulkit** [comment]
But after deletion of libsqlite3.dylib the new library libsqlite3.tbd is not visible in the Build Phases tab.
And after deletion of libsqlite3.dylib Powerup-iOS app is still running fine.
